"""
src/features/engineer.py
─────────────────────────
Feature engineering for demand forecasting. 
Transforms cleaned data into training-ready features.
"""

from __future__ import annotations

import logging
from pyspark.sql import DataFrame
from pyspark.sql import functions as F
from pyspark.sql.window import Window

logger = logging.getLogger(__name__)


def add_lag_features(df: DataFrame) -> DataFrame:
    """
    Add lagged demand features. Lag-2 is prioritized as it often captures 
    rebound effects in this dataset.
    """
    ts_window = Window.partitionBy("Product_Code", "Warehouse").orderBy("Date")
    
    df = df.withColumn(
        "demand_T_minus_2",
        F.lag("Order_Demand", 2).over(ts_window)
    )
    
    logger.info("Lag features (T-2) added.")
    return df


def add_rolling_features(df: DataFrame, window_size: int = 7) -> DataFrame:
    """
    Add rolling statistics (mean, stddev) over a sliding window.
    """
    ts_window = Window.partitionBy("Product_Code", "Warehouse").orderBy("Date")
    rolling_window = ts_window.rowsBetween(-(window_size - 1), 0)
    
    df = df.withColumn(
        f"rolling_{window_size}d_stddev",
        F.stddev("Order_Demand").over(rolling_window)
    ).withColumn(
        f"rolling_{window_size}d_mean",
        F.mean("Order_Demand").over(rolling_window)
    )
    
    logger.info("Rolling window features (%dd) added.", window_size)
    return df


def add_binary_indicators(df: DataFrame) -> DataFrame:
    """
    Add binary flags for seasonality and key days.
    """
    # Assuming day_of_week 1=Sunday...7=Saturday or similar. 
    # Usually we look for Monday (2) or weekends. 
    # Current implementation in training_pipeline assumes Monday = 1.
    
    df = df.withColumn(
        "is_q4",
        F.when(F.col("month").isin(10, 11, 12), 1).otherwise(0)
    ).withColumn(
        "is_monday",
        F.when(F.col("day_of_week") == 2, 1).otherwise(0) # 2 is often Monday in Spark
    )
    
    logger.info("Binary indicator features (Q4, Monday) added.")
    return df


def handle_feature_nulls(df: DataFrame) -> DataFrame:
    """
    Fill nulls generated by lag/rolling windows.
    """
    cols_to_fix = [c for c in df.columns if "demand_T" in c or "rolling" in c]
    df = df.fillna(0, subset=cols_to_fix)
    
    logger.info("Feature nulls filled with 0 for: %s", cols_to_fix)
    return df


def engineer_features(df: DataFrame, cfg: dict) -> DataFrame:
    """
    Master feature engineering function.
    """
    logger.info("Starting feature engineering...")
    
    df = add_lag_features(df)
    df = add_rolling_features(df, window_size=7)
    df = add_binary_indicators(df)
    df = handle_feature_nulls(df)
    
    logger.info("Feature engineering complete. Total columns: %d", len(df.columns))
    return df


# For backward compatibility with the original name
def build_temporal_features(df: DataFrame) -> DataFrame:
    return engineer_features(df, {})
